FROM ubuntu:16.04 as builder

WORKDIR /root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common build-essential checkinstall zlib1g-dev wget fuse libfuse2 desktop-file-utils libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 uuid-dev libopencore-amrwb-dev libopencore-amrnb-dev libopus-dev libasound2-dev

RUN cd /usr/local/src/ && wget https://www.openssl.org/source/openssl-1.1.1s.tar.gz && tar -xf openssl-1.1.1s.tar.gz && cd openssl-1.1.1s && ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib && make && make install && echo "/usr/local/ssl/lib" >> /etc/ld.so.conf.d/openssl-1.1.1s.conf && ldconfig -v 

RUN add-apt-repository ppa:beineri/opt-qt-5.15.2-xenial
RUN apt-get update && apt-get install -y qt515base qt515websockets

RUN cd /usr/local/bin && wget -c -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage && chmod a+x linuxdeployqt-continuous-x86_64.AppImage

ENV QT_BASE_DIR=/opt/qt515
ENV QTDIR=$QT_BASE_DIR
ENV PATH=$QT_BASE_DIR/bin:/usr/local/ssl/bin:$PATH
ENV LD_LIBRARY_PATH=$QT_BASE_DIR/lib:/usr/local/ssl/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH=$LD_LIBRARY_PATH
ENV PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:/usr/local/ssl/lib/pkgconfig:$PKG_CONFIG_PATH

WORKDIR /home/root/

CMD ["/bin/bash"]
