name: Build AWAH-SIP Codec
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
        
      - name: Install fancy dependencies
        run:  sudo apt install fuse libfuse2 desktop-file-utils libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 uuid-dev libopencore-amrwb-dev libopencore-amrnb-dev libopus-dev libasound2-dev libssl-dev
        
      - name: Install SSL 1.1.1
        run:  wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.17_amd64.deb && sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.17_amd64.deb 

      - name: QMake
        run: mkdir build && cd build && qmake CONFIG+=release PREFIX=/usr ../AWAH-SIP_Codec.pro
        
      - name: Make
        run:  cd build && make -j$(nproc)
        
      - name: MakeInstall
        run:  cd build && make INSTALL_ROOT=AppDir -j$(nproc) install && pwd && ls -la && cd AppDir && mv -v AppDir .. && cd .. && ls -la
        
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AWAH-SIP|AWAH-SIP_Codec|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AWAH-SIP_Codec_${{ github.sha }}-x86_64.AppImage
          path: build/AWAH-SIP_Codec-*-x86_64.AppImage
  
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"

      - name: Install Opencore & OpenSSL
        run: brew install opencore-amr openssl@1.1

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
        
      - run:  mkdir build

      - name: QMake
        run: cd build && qmake ../AWAH-SIP_Codec.pro
        
      - name: Make
        run:  cd build && make && mv AWAH-SIP_Codec.app AWAH-SIP_Codec_${{ github.sha }}.app
        
      - name: MacDeployQT
        run:  cd build && macdeployqt AWAH-SIP_Codec_${{ github.sha }}.app -dmg
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AWAH-SIP_Codec_${{ github.sha }}.dmg
          path: build/AWAH-SIP_Codec_*.dmg
        
  Windows:
    runs-on: windows-2019
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"
          arch: "win32_msvc2019"
        
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: check vcvarsall.bat
        run: dir "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        shell: cmd

      - name: QMake & Make
        run: |
          call "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
          ..\Qt\5.15.2\msvc2019\bin\qmake.exe AWAH-SIP_Codec.pro -spec win32-msvc
          nmake
        shell: cmd
        
      - name: WinDeployQT
        run:  md deploy && copy release\AWAH-SIP_Codec.exe deploy\ && windeployqt --release --no-translations --compiler-runtime deploy\AWAH-SIP_Codec.exe
        
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: deploy
          dest: AWAH-SIP_Codec-${{ github.sha }}.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AWAH-SIP_Codec-${{ github.sha }}.zip
          path: AWAH-SIP_Codec-*.zip
